services:
  - type: web
    name: campus-recruitment-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        value: https://xdetsdkofiogpziwzmip.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_uN3CiBXDA3-PuBkXR-APPA_17h4bwWR
      - key: JWT_SECRET
        value: CampusHire_SuperSecret_JWT_Key_2025!
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://campusrecruitmentsystem.netlify.app,https://automated-campus-recruitment-system-with.onrender.com
